# Keyring and auth
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Clipboard history
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Auto delete trash 30 days old
exec-once = trash-empty 30

# Cursors
exec-once = hyprctl setcursor sweet-cursors 24
exec-once = gsettings set org.gnome.desktop.interface cursor-theme 'sweet-cursors'

# Location provider and night light
exec-once = /usr/lib/geoclue-2.0/demos/agent
exec-once = sleep 1 && gammastep

# Idle inhibit when audio playing
exec-once = sway-audio-idle-inhibit --ignore-source-outputs cava

# Forward bluetooth media commands to MPRIS
exec-once = mpris-proxy

# Resize and move picture in picture windows
exec-once = caelestia pip -d

# Reload hyprland when config changes (to regenerate everything)
exec-once = ~/.config/hypr/scripts/monitor-config.fish

# Start shell
exec-once = caelestia shell -d

# Fun
exec-once = activate-linux -s 0.8
exec-once = rquickshare
exec-once = /opt/urserver/urserver --daemon
exec-once = xrdb ~/.Xresources


# Idle daemon
exec-once = hypridle

# Power Button manager
exec-once = systemd-inhibit --who="Hyprland config" --why="wlogout keybind" --what=handle-power-key --mode=block sleep infinity & echo $! > /tmp/.hyprland-systemd-inhibit
exec-shutdown = kill -9 "$(cat /tmp/.hyprland-systemd-inhibit)
# bind = , XF86PowerOff, exec, systemctl suspend # in `keybinds.conf`
